name: Rust (Common)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  msrv:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - run: >-
          cargo hack check --rust-version --workspace --all-targets
          --ignore-private
        working-directory: common

  semver-checks:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          manifest-path: common/Cargo.toml

  rustfmt:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rustfmt checks
        run: cargo fmt --check
        working-directory: common

  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Cargo Build
        run: cargo build --verbose
        working-directory: common
      - name: Run tests
        run: cargo test --verbose
        working-directory: common
